### ISSUE TITLE
Checklist for new release of origin.js

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#101]
Creating checklist of tasks to be completed for each new release, ideally at the end of each sprint.

A lot of these steps could be automated someday, but for now probably good to do it by hand a few times. 

## Confirm readiness
- [X] Check version number in `package.json`
- [X] demo dapp: Confirm all tests passing 
- [X] origin-js: Confirm js tests passing
  - `npm run setup`
  - `npm start`
- [X] platform: Confirm smart contracts (.sol) tests passing
  - `cd contracts && truffle test`

## Publish
- [x] (If contracts are changed) 
  - [X] Deploy new smart contracts to Rinkeby. Be sure addresses are listed in ABI files. 
    - `export ROPSTEN_MNEMONIC="<mnemonic>"`
    - `truffle migrate --network ropsten`
  - [X] Deploy new smart contracts to Ropsten. Be sure addresses are listed in ABI files. 
    - `export RINKEBY_MNEMONIC="<mnemonic>"`
    - `truffle migrate --network rinkeby`
  - [ ] Migrate data from old contracts to new. (Once we get around to writing migrations!)
- [x] Build origin.js (in `dist/origin.js`)
- [x] demo-dapp: Merge `develop` into `master` and push
- [x] platform: Merge `develop` into `master` and push
- [x] platform: Create new [GitHub release](https://github.com/OriginProtocol/platform/releases) with origin.js code,
  - [x] Version in form `v0.1.2` (This will add git tag on `master`)
  - [x] Include addresses of smart contracts in description
- [x] demo-dapp: Add git tag to `master` to match platform and push.
  - `git tag -a v0.1.2`
  - `git push`
- [x] [Publish to npm](https://docs.npmjs.com/cli/publish). (`npm publish`)
- [ ] Deploy new version of dapp to heroku (url to be determined)

## Special case 
- [x] Deprecate `@originprotocol/origin` - https://stackoverflow.com/a/28841779/59913
- [X] Re-publish as `origin`

## Follow-up
- [x] Confirm published `origin.js` file is accessible via `code.originprotocol.com` redirect
  - https://unpkg.com/origin@0.5.8/dist/origin.js for now
- [ ] demo-dapp: Confirm that "one-line setup & run" command works on `master` branch shown by default
- [x] Confirm that demo dapp using npm package works and can find contracts
- [x] platform: Increment version number on `develop` to for next release
- [x] demo-dapp: Increment version number on `develop` to for next release
- [ ] Review docs for needed updates. Confirm example code on playground site (jsfiddle?) still work.
- [ ] Copy this to-do list into new issue for next sprint.

**Comment by wanderingstan** [comment]
Copied this into latest sprint. We'll see how it goes!

**Comment by wanderingstan** [comment]
Rinkeby result:
```
~/Origin/platform/contracts$ truffle migrate --network rinkeby
Using network 'rinkeby'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xfceacb3782f52faa590f19a2bc377baad31aeb2630742b4a4dc472ea2fcbf9cf
  Migrations: 0x46a1e3eafad0e54dbbdcc4ab1c447bcebc4bf842
Saving successful migration to network...
  ... 0x5b4bedc41f2c52775a5e0a0029ab6669ecd1d144fb1bcbe9c5e90ff362266bb1
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying PurchaseLibrary...
  ... 0x163416b5cc7113d6148d8203cc6804d63fdd008eee41f710029d4da79fcc866e
  PurchaseLibrary: 0xf06038afe9ed6daa8f9d2ba4b0dc3bd4fe6266e9
  Linking PurchaseLibrary to ListingsRegistry
  Linking PurchaseLibrary to Listing
  Deploying ListingsRegistry...
  ... 0xf719a2b523d14fdefb2af79a23866e23988b4bf2d6acbc6e832561852e0dd899
  ListingsRegistry: 0xbc16a0193de4cbbb39c188850df711340d151b3f
  Deploying UserRegistry...
  ... 0x9156609f8787fc345e32f80f667e3947caf42c7168480f06cedc21ea10082df2
  UserRegistry: 0x90d36e62f94fb2a59206d113b938671b758c1c97
Saving successful migration to network...
  ... 0xe27ccf31f1cc915b08fed870029d3f4095380b9ab09ac58e084d8ca148d08007
Saving artifacts...
Running migration: 3_create_sample_listings.js
network rinkeby
Saving successful migration to network...
  ... 0x71e68b5d8570ba37cc88e01f97411e2e59288b6089bf109b2a211a5fe1435505
```

**Comment by wanderingstan** [comment]
Ropsten:
```
~/Origin/platform/contracts$ truffle migrate --network ropsten
Using network 'ropsten'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xecd68f6e1d2005be54e066714337a2a06320edf609ee048b729eca6a06acf14d
  Migrations: 0x90d36e62f94fb2a59206d113b938671b758c1c97
Saving successful migration to network...
  ... 0xd8940638c12640d3f4224dbb0d8ae5086cb272ae7a5dcc194a49bcd6f9461e1e
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying PurchaseLibrary...
  ... 0xf310456ee2e1a0c30a1a40d9cda91f2b348e9c3c57651dd15c19709fbdaa42cd
  PurchaseLibrary: 0x70e8efa36452239f773218a70cf6710f5f8fd40e
  Linking PurchaseLibrary to ListingsRegistry
  Linking PurchaseLibrary to Listing
  Deploying ListingsRegistry...
  ... 0xbba2511c77143bb202e751c091378c991249099e0c12a2185d235e793379a5c7
  ListingsRegistry: 0xac824c89eab1b2e1b92f0e1675b49d5ddaee06fe
  Deploying UserRegistry...
  ... 0xae40e84971a6f557d854c9e7e7478dc26ac2dc16974c27d8a2b7c3fb06c0fbb4
  UserRegistry: 0xe6f31abe55f5d33b7acdf7b545ade50d95c7f3a3
Saving successful migration to network...
  ... 0x2514551419f1af0f277b04372a8545890c87c820f34100f85996dec3e4889acb
Saving artifacts...
Running migration: 3_create_sample_listings.js
network ropsten
Saving successful migration to network...
  ... 0x8581369c36bd5583727bf4c15a376fa0627c54c4dafeb3801842d5080dba104c
Saving artifacts...
```

**Comment by wanderingstan** [comment]
All was done according to the holy checklist. Release 0.5.8 is hereby released, and this issue thereby, and in good conscious, closed.
